apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "livekit-server.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
data:
  config.yaml: |
{{ toYaml .Values.livekit | indent 4 }}
